// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace FlixHub.Core.Api.Migrations
{
    [DbContext(typeof(FlixHubDbContext))]
    [Migration("20251015073916_FlixHubDb_Init")]
    partial class FlixHubDb_Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Content", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Content.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Awards")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Awards wining.");

                    b.Property<string>("BackdropPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Backdrop image path or URL.");

                    b.Property<long?>("Budget")
                        .HasColumnType("bigint")
                        .HasComment("Movie/TV Budget.");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ISO 3166-1 country code.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("IMDb ID.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Logo image path or URL.");

                    b.Property<string>("OriginalLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("ISO 639-1 language code.");

                    b.Property<string>("OriginalTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Original title or name in original language.");

                    b.Property<string>("Overview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Summary / description.");

                    b.Property<decimal?>("Popularity")
                        .HasColumnType("decimal(12,6)")
                        .HasComment("TMDb popularity score.");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Poster image path or URL.");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("date")
                        .HasComment("Movie: release_date / TV: first_air_date.");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer")
                        .HasComment("Runtime in minutes (movie or avg episode runtime).");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasComment("Release status: Released, Ended, Returning Series.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Display title of the content.");

                    b.Property<int>("TmdbId")
                        .HasColumnType("integer")
                        .HasComment("TMDb ID (unique for movie/tv).");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasComment("Content type: Movie or TV.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Content.");

                    b.Property<decimal?>("VoteAverage")
                        .HasColumnType("decimal(4,2)")
                        .HasComment("TMDb average vote rating.");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("integer")
                        .HasComment("TMDb vote count.");

                    b.HasKey("Id");

                    b.HasIndex("TmdbId")
                        .IsUnique();

                    b.ToTable("Content", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentCast", b =>
                {
                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content (movie or TV).");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Person.");

                    b.Property<string>("Character")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Character name played by the actor.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentCast.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasComment("Billing order of the cast member from TMDb.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentCast.");

                    b.HasKey("ContentId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContentCast", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentCrew", b =>
                {
                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content (movie or TV).");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Person.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Department this person worked in (Directing, Writing, Production).");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentCrew.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Specific job title (Director, Writer, Producer).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentCrew.");

                    b.HasKey("ContentId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ContentCrew", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentGenre", b =>
                {
                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content (movie or TV).");

                    b.Property<long>("GenreId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Genre.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Genre.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Genre.");

                    b.HasKey("ContentId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ContentGenre", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentImage.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content entity.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("File path for the image from TMDb.");

                    b.Property<int>("Height")
                        .HasColumnType("integer")
                        .HasComment("Image height in pixels.");

                    b.Property<string>("Language")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasComment("Language code (iso_639_1).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Image type: 1=Poster, 2=Backdrop, 3=Logo, 4=Still.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentImage.");

                    b.Property<int>("Width")
                        .HasColumnType("integer")
                        .HasComment("Image width in pixels.");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("ContentImage", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentRating", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentRating.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content entity.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasComment("Rating source: 1=IMDb, 2=RottenTomatoes, 3=Metacritic.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentRating.");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Rating value string from OMDb, e.g. '8.3/10', '98%', '88/100'.");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("ContentRating", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentSeason", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Season.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("date")
                        .HasComment("First air date of the season.");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content entity (TV series).");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<int?>("EpisodeCount")
                        .HasColumnType("integer")
                        .HasComment("Number of episodes in this season (if known).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<string>("Overview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Overview/description of the season.");

                    b.Property<string>("PosterPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Poster image path from TMDb.");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasComment("Season number, starting at 1.");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Optional title of the season.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Season.");

                    b.HasKey("Id");

                    b.HasIndex("ContentId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("ContentSeason", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentSyncLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentSyncLog.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the sync for this year/month/type is completed.");

                    b.Property<int>("LastCompletedPage")
                        .HasColumnType("integer")
                        .HasComment("Last successfully completed page number for this sync batch.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasComment("Month of the sync batch (1–12).");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("Optional notes or error details for debugging.");

                    b.Property<int?>("TotalPages")
                        .HasColumnType("integer")
                        .HasComment("Total pages available for this sync batch (from TMDb).");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Content type being synced: 1=Movie, 2=Series.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentSyncLog.");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasComment("Year of the sync batch.");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Year", "Month")
                        .IsUnique();

                    b.ToTable("ContentSyncLog", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for ContentVideo.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content entity.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the video is an official release.");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("External video key (e.g., YouTube video id).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasComment("Title of the video.");

                    b.Property<int>("Site")
                        .HasColumnType("integer")
                        .HasComment("Video site: 1=YouTube, 2=Vimeo.");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("Video type: 1=Trailer, 2=Teaser, 3=Clip, 4=Featurette.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for ContentVideo.");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.ToTable("ContentVideo", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.DailyApiUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for DailyApiUsage.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContentType")
                        .HasColumnType("integer")
                        .HasComment("Content type for which requests were made: 1=Movie, 2=Series.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date of the API usage tracking (daily basis).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<int>("RequestCount")
                        .HasColumnType("integer")
                        .HasComment("Number of API requests made for this content type on this date.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for DailyApiUsage.");

                    b.HasKey("Id");

                    b.HasIndex("Date", "ContentType")
                        .IsUnique();

                    b.ToTable("DailyApiUsage", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Episode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Episode.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("date")
                        .HasComment("Air date of the episode.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasComment("Episode number within the season.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<string>("Overview")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Overview/description of the episode.");

                    b.Property<int?>("Runtime")
                        .HasColumnType("integer")
                        .HasComment("Runtime of the episode in minutes.");

                    b.Property<long>("SeasonId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Season entity.");

                    b.Property<string>("StillPath")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("Still image path from TMDb.");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Title of the episode.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Episode.");

                    b.Property<decimal?>("VoteAverage")
                        .HasColumnType("decimal(4,2)")
                        .HasComment("Average vote score for the episode.");

                    b.Property<int?>("VoteCount")
                        .HasColumnType("integer")
                        .HasComment("Number of votes for the episode.");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Episode", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.EpisodeCast", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for EpisodeCast.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Character")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Character name played by the actor in this episode.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Episode entity.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasComment("Billing order of the actor in this episode.");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Person entity.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for EpisodeCast.");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PersonId");

                    b.ToTable("EpisodeCast", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.EpisodeCrew", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for EpisodeCrew.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Department of the crew member (Directing, Writing, etc.).");

                    b.Property<long>("EpisodeId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Episode entity.");

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Specific job title of the crew member.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Person entity.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for EpisodeCrew.");

                    b.HasKey("Id");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PersonId");

                    b.ToTable("EpisodeCrew", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Genre.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Name of the genre (Drama, Action, etc.).");

                    b.Property<int>("TmdbReferenceId")
                        .HasColumnType("integer")
                        .HasComment("Optional TMDb genre id for mapping.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Genre.");

                    b.HasKey("Id");

                    b.HasIndex("TmdbReferenceId")
                        .IsUnique();

                    b.ToTable("Genre", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Person.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Biography")
                        .HasColumnType("text")
                        .HasComment("Person Biography.");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date")
                        .HasComment("Birth date of the person.");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("text")
                        .HasComment("Birth place of the person.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("date")
                        .HasComment("Death date of the person.");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasComment("Gender: 0=Unknown, 1=Female, 2=Male, 3=NonBinary.");

                    b.Property<string>("KnownForDepartment")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Department this person is best known for (Acting, Directing, Writing).");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasComment("Full name of the person.");

                    b.Property<string>("PersonalPhoto")
                        .HasColumnType("text")
                        .HasComment("Profile image path from TMDb.");

                    b.Property<long>("TmdbId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Person.");

                    b.HasKey("Id");

                    b.ToTable("Person", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.SystemUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Unique identifier for the SystemUser record.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who created the record.");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasComment("Email address of the system user.");

                    b.Property<string>("EmailVerificationCode")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasComment("Email verification code for user.");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasComment("First name of the system user.");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the user is active.");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasComment("Indicates whether the user is verified.");

                    b.Property<Guid?>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the user in the Keycloak system.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("Username or identifier of the user who last modified the record.");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasComment("Last name of the system user.");

                    b.Property<string>("Preferences")
                        .HasColumnType("jsonb")
                        .HasComment("User preferences stored as JSON.");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar")
                        .HasComment("Username of the system user.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the SystemUser.");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SystemUser", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Watchlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasComment("Internal primary key for Watchlist.");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the content was added to the watchlist.");

                    b.Property<long>("ContentId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to Content entity.");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was created.");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who created the record.");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Date and time when the record was last modified.");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasComment("User who last modified the record.");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("Foreign key to SystemUser entity.");

                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Unique UUID identifier for Watchlist.");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("UserId", "ContentId")
                        .IsUnique();

                    b.ToTable("Watchlist", "public");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentCast", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Casts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentCrew", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Crews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentGenre", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Genres")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentImage", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Images")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentRating", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentSeason", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Seasons")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentVideo", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", null)
                        .WithMany("Videos")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Episode", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.ContentSeason", null)
                        .WithMany("Episodes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.EpisodeCast", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Episode", null)
                        .WithMany("Casts")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.EpisodeCrew", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Episode", null)
                        .WithMany("Crews")
                        .HasForeignKey("EpisodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Watchlist", b =>
                {
                    b.HasOne("FlixHub.Core.Api.Entities.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlixHub.Core.Api.Entities.SystemUser", null)
                        .WithMany("Watchlist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Content", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Crews");

                    b.Navigation("Genres");

                    b.Navigation("Images");

                    b.Navigation("Ratings");

                    b.Navigation("Seasons");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.ContentSeason", b =>
                {
                    b.Navigation("Episodes");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.Episode", b =>
                {
                    b.Navigation("Casts");

                    b.Navigation("Crews");
                });

            modelBuilder.Entity("FlixHub.Core.Api.Entities.SystemUser", b =>
                {
                    b.Navigation("Watchlist");
                });
#pragma warning restore 612, 618
        }
    }
}
